# Generated by Django 4.2.11 on 2024-03-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField()),
                ('scan_start_time', models.DateTimeField(auto_now_add=True)),
                ('scan_end_time', models.DateTimeField(blank=True, null=True)),
                ('results', models.TextField()),
            ],
        ),
    ]
